"""autogenerated by genpy from al5d_arm/fwdkin.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class fwdkin(genpy.Message):
  _md5sum = "b211c9f75d79ac5c8fd4c47719f57bb7"
  _type = "al5d_arm/fwdkin"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#forwardkin al5d arm

float32 base_angle
float32 shoulder_angle
float32 elbow_angle
float32 wrist_angle
float32 gripper_percent

"""
  __slots__ = ['base_angle','shoulder_angle','elbow_angle','wrist_angle','gripper_percent']
  _slot_types = ['float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       base_angle,shoulder_angle,elbow_angle,wrist_angle,gripper_percent

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(fwdkin, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.base_angle is None:
        self.base_angle = 0.
      if self.shoulder_angle is None:
        self.shoulder_angle = 0.
      if self.elbow_angle is None:
        self.elbow_angle = 0.
      if self.wrist_angle is None:
        self.wrist_angle = 0.
      if self.gripper_percent is None:
        self.gripper_percent = 0.
    else:
      self.base_angle = 0.
      self.shoulder_angle = 0.
      self.elbow_angle = 0.
      self.wrist_angle = 0.
      self.gripper_percent = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_5f.pack(_x.base_angle, _x.shoulder_angle, _x.elbow_angle, _x.wrist_angle, _x.gripper_percent))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.base_angle, _x.shoulder_angle, _x.elbow_angle, _x.wrist_angle, _x.gripper_percent,) = _struct_5f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_5f.pack(_x.base_angle, _x.shoulder_angle, _x.elbow_angle, _x.wrist_angle, _x.gripper_percent))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.base_angle, _x.shoulder_angle, _x.elbow_angle, _x.wrist_angle, _x.gripper_percent,) = _struct_5f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_5f = struct.Struct("<5f")
