/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/joseph/catkin_ws/src/al5d_arm/msg/invkin.msg
 *
 */


#ifndef AL5D_ARM_MESSAGE_INVKIN_H
#define AL5D_ARM_MESSAGE_INVKIN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace al5d_arm
{
template <class ContainerAllocator>
struct invkin_
{
  typedef invkin_<ContainerAllocator> Type;

  invkin_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , grip_angle(0.0)  {
    }
  invkin_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , grip_angle(0.0)  {
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _grip_angle_type;
  _grip_angle_type grip_angle;




  typedef boost::shared_ptr< ::al5d_arm::invkin_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::al5d_arm::invkin_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct invkin_

typedef ::al5d_arm::invkin_<std::allocator<void> > invkin;

typedef boost::shared_ptr< ::al5d_arm::invkin > invkinPtr;
typedef boost::shared_ptr< ::al5d_arm::invkin const> invkinConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::al5d_arm::invkin_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::al5d_arm::invkin_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace al5d_arm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'al5d_arm': ['/home/joseph/catkin_ws/src/al5d_arm/msg'], 'std_msgs': ['/opt/ros/groovy/share/std_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::al5d_arm::invkin_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::al5d_arm::invkin_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::al5d_arm::invkin_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::al5d_arm::invkin_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::al5d_arm::invkin_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::al5d_arm::invkin_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::al5d_arm::invkin_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23c3ddbec420d3c96d407c67a170ed7f";
  }

  static const char* value(const ::al5d_arm::invkin_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23c3ddbec420d3c9ULL;
  static const uint64_t static_value2 = 0x6d407c67a170ed7fULL;
};

template<class ContainerAllocator>
struct DataType< ::al5d_arm::invkin_<ContainerAllocator> >
{
  static const char* value()
  {
    return "al5d_arm/invkin";
  }

  static const char* value(const ::al5d_arm::invkin_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::al5d_arm::invkin_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#inversekin al5d arm\n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
float32 grip_angle \n\
\n\
";
  }

  static const char* value(const ::al5d_arm::invkin_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::al5d_arm::invkin_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.grip_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct invkin_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::al5d_arm::invkin_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::al5d_arm::invkin_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "grip_angle: ";
    Printer<float>::stream(s, indent + "  ", v.grip_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AL5D_ARM_MESSAGE_INVKIN_H
